<!-- Copyright (c) 2000-2002  BEA Systems, Inc. All Rights Reserved. -->


<table width="100%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td class="headerBgColor"><img src="<wf:createResourceURL resource='<%=imagesPath + "portal_header.gif"%>'/>" border="0"></td>
  </tr>
  <tr>
    <td class="titlebar" width="100%" valign="middle" align="right">
      <a href="index.jsp"><img src="<wf:createResourceURL resource='<%=imagesPath + "return_to_portal.gif"%>'/>" border="0" vspace="6" hspace="6"></a>
    </td>
  </tr>
</table>